#ifndef STATUS_CODES_H
#define STATUS_CODES_H

// 200
#define OK "200 OK"

// 300

// 400
#define BAD_REQUEST "400 BAD REQUEST"
#define UNAUTHORIZED "401 UNAUTHORIZED"
#define FORBIDDEN "403 FORBIDDEN"
#define FILE_NOT_FOUND "404 FILE NOT FOUND"
#define METHOD_NOT_ALLOWED "405"
#define IM_A_TEAPOT "418 I'M A TEAPOT"

// 500
#define INTERNAL_SERVER_ERROR "500 INTERNAL SERVER ERROR"
#define NOT_IMPLEMENTED "501 NOT IMPLEMENTED"
#define UNKNOWN_ERROR "520 UNKNOWN ERROR"

#endif
